# Generated by Django 3.2.8 on 2021-10-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('hash', models.CharField(default='RXqP4fhvr6yuKNd', max_length=15, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.URLField()),
            ],
        ),
    ]
