# Generated by Django 3.2.8 on 2021-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211026_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='hash',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
